In [1]:
from models import hiera_tiny_224, transnext_tiny
import torch
import torchvision.models as models
from timm.models import create_model

/home/user/miniconda3/envs/endo_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


swattention package not found, loading PyTorch native version of Aggregated Attention


/home/user/Endo/limuc_proj/models/dinov2/layers/swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
/home/user/Endo/limuc_proj/models/dinov2/layers/attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
/home/user/Endo/limuc_proj/models/dinov2/layers/block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")


In [34]:
model = torch.nn.Module()
model.add_module(name="backbone", module=torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14'))
model.add_module(name="head", module=torch.nn.Linear(in_features=384, out_features=2, bias=True))

# dinov2_vits14 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14')
# dinov2_vits14.head = torch.nn.Linear(in_features=384, out_features=2, bias=True)
for param_name, param in model.named_parameters():
    print(param_name, param)

Using cache found in /home/user/.cache/torch/hub/facebookresearch_dinov2_main


backbone.cls_token Parameter containing:
tensor([[[-6.8410e-03,  2.6086e-03,  1.6149e-02, -2.5937e-03, -1.6370e-03,
          -2.3220e-03,  2.0959e-04, -8.5568e-04,  2.7370e-03,  3.4901e-03,
          -4.6377e-03, -1.0370e-02, -7.4891e-04, -1.3678e-02, -4.3106e-03,
          -2.9372e-03, -1.2939e-03,  3.0098e-03, -3.4187e-02,  2.2269e-03,
          -6.4373e-03,  3.5713e-02,  6.9370e-03,  2.7280e-04,  3.2431e-03,
           2.6636e-02, -3.0152e-04, -6.1275e-04, -2.3360e-03, -1.9538e-02,
          -3.0734e-03,  3.4016e-04,  3.1648e-03,  1.9603e-03,  3.9863e-03,
           4.8807e-03,  1.2272e-03,  1.2598e-03,  4.4603e-03, -3.4178e-04,
           2.7807e-03, -2.1892e-02,  1.6567e-03, -8.4406e-03,  4.7966e-03,
          -1.7167e-04, -4.3230e-03, -5.8655e-04,  1.6425e-03,  1.9382e-02,
          -2.6624e-03, -6.7002e-04,  1.7988e-03,  2.5716e-03, -1.8315e-03,
           1.2139e-02,  2.5226e-03, -1.1061e-04,  4.1116e-03, -3.5940e-03,
          -3.0501e-03, -1.4037e-02,  4.9184e-03,  2.6615e-0

In [29]:
input = torch.randn(1, 3, 224, 224)
output = dinov2_vits14(input)
print(output.shape)
print(torch.unique(output))

torch.Size([1, 2])
tensor([-0.0269,  1.1602], grad_fn=<Unique2Backward0>)


In [4]:
output = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).float()
softmax = torch.nn.Softmax(dim=0)
output = softmax(output)
print(output)
output = softmax(output)
print(output)
output = softmax(output)
print(output)

tensor([7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
        3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01])
tensor([0.0886, 0.0886, 0.0887, 0.0888, 0.0890, 0.0897, 0.0915, 0.0965, 0.1118,
        0.1668])
tensor([0.0988, 0.0988, 0.0988, 0.0989, 0.0989, 0.0989, 0.0991, 0.0996, 0.1012,
        0.1069])


In [2]:
from models.timesformer.timesformer import get_vit_base_patch16_224

In [3]:
model = get_vit_base_patch16_224()
for param_name, param in model.named_parameters():
    print(param_name)

cls_token
pos_embed
time_embed
patch_embed.proj.weight
patch_embed.proj.bias
blocks.0.norm1.weight
blocks.0.norm1.bias
blocks.0.attn.qkv.weight
blocks.0.attn.qkv.bias
blocks.0.attn.proj.weight
blocks.0.attn.proj.bias
blocks.0.temporal_norm1.weight
blocks.0.temporal_norm1.bias
blocks.0.temporal_attn.qkv.weight
blocks.0.temporal_attn.qkv.bias
blocks.0.temporal_attn.proj.weight
blocks.0.temporal_attn.proj.bias
blocks.0.temporal_fc.weight
blocks.0.temporal_fc.bias
blocks.0.norm2.weight
blocks.0.norm2.bias
blocks.0.mlp.fc1.weight
blocks.0.mlp.fc1.bias
blocks.0.mlp.fc2.weight
blocks.0.mlp.fc2.bias
blocks.1.norm1.weight
blocks.1.norm1.bias
blocks.1.attn.qkv.weight
blocks.1.attn.qkv.bias
blocks.1.attn.proj.weight
blocks.1.attn.proj.bias
blocks.1.temporal_norm1.weight
blocks.1.temporal_norm1.bias
blocks.1.temporal_attn.qkv.weight
blocks.1.temporal_attn.qkv.bias
blocks.1.temporal_attn.proj.weight
blocks.1.temporal_attn.proj.bias
blocks.1.temporal_fc.weight
blocks.1.temporal_fc.bias
blocks.1.norm

In [9]:
input = torch.randn(4, 3, 224, 224)
output = model(input)
print(output.shape)

torch.Size([4, 4])


In [4]:
ckpt = torch.load('models/timesformer/pretrain_weights/endo_fm.pth')["student"]

# remove keys with prefix "module."
new_ckpt = {}
for key in ckpt.keys():
    new_key = key.replace("module.backbone.", "")
    if "head" not in new_key:
        new_ckpt[new_key] = ckpt[key]

In [5]:
for key in new_ckpt.keys():
    print(key)

cls_token
pos_embed
time_embed
patch_embed.proj.weight
patch_embed.proj.bias
blocks.0.norm1.weight
blocks.0.norm1.bias
blocks.0.attn.qkv.weight
blocks.0.attn.qkv.bias
blocks.0.attn.proj.weight
blocks.0.attn.proj.bias
blocks.0.temporal_norm1.weight
blocks.0.temporal_norm1.bias
blocks.0.temporal_attn.qkv.weight
blocks.0.temporal_attn.qkv.bias
blocks.0.temporal_attn.proj.weight
blocks.0.temporal_attn.proj.bias
blocks.0.temporal_fc.weight
blocks.0.temporal_fc.bias
blocks.0.norm2.weight
blocks.0.norm2.bias
blocks.0.mlp.fc1.weight
blocks.0.mlp.fc1.bias
blocks.0.mlp.fc2.weight
blocks.0.mlp.fc2.bias
blocks.1.norm1.weight
blocks.1.norm1.bias
blocks.1.attn.qkv.weight
blocks.1.attn.qkv.bias
blocks.1.attn.proj.weight
blocks.1.attn.proj.bias
blocks.1.temporal_norm1.weight
blocks.1.temporal_norm1.bias
blocks.1.temporal_attn.qkv.weight
blocks.1.temporal_attn.qkv.bias
blocks.1.temporal_attn.proj.weight
blocks.1.temporal_attn.proj.bias
blocks.1.temporal_fc.weight
blocks.1.temporal_fc.bias
blocks.1.norm

In [6]:
model.load_state_dict(new_ckpt, strict=False)

_IncompatibleKeys(missing_keys=['head.weight', 'head.bias'], unexpected_keys=[])

In [27]:
vit_small = create_model('vit_small_patch16_224', num_classes=4)

In [28]:
for param_name, param in vit_small.named_parameters():
    print(param_name)

cls_token
pos_embed
patch_embed.proj.weight
patch_embed.proj.bias
blocks.0.norm1.weight
blocks.0.norm1.bias
blocks.0.attn.qkv.weight
blocks.0.attn.qkv.bias
blocks.0.attn.proj.weight
blocks.0.attn.proj.bias
blocks.0.norm2.weight
blocks.0.norm2.bias
blocks.0.mlp.fc1.weight
blocks.0.mlp.fc1.bias
blocks.0.mlp.fc2.weight
blocks.0.mlp.fc2.bias
blocks.1.norm1.weight
blocks.1.norm1.bias
blocks.1.attn.qkv.weight
blocks.1.attn.qkv.bias
blocks.1.attn.proj.weight
blocks.1.attn.proj.bias
blocks.1.norm2.weight
blocks.1.norm2.bias
blocks.1.mlp.fc1.weight
blocks.1.mlp.fc1.bias
blocks.1.mlp.fc2.weight
blocks.1.mlp.fc2.bias
blocks.2.norm1.weight
blocks.2.norm1.bias
blocks.2.attn.qkv.weight
blocks.2.attn.qkv.bias
blocks.2.attn.proj.weight
blocks.2.attn.proj.bias
blocks.2.norm2.weight
blocks.2.norm2.bias
blocks.2.mlp.fc1.weight
blocks.2.mlp.fc1.bias
blocks.2.mlp.fc2.weight
blocks.2.mlp.fc2.bias
blocks.3.norm1.weight
blocks.3.norm1.bias
blocks.3.attn.qkv.weight
blocks.3.attn.qkv.bias
blocks.3.attn.proj.wei

In [29]:
ckpt = torch.load("./pretrain_weights/VITS_GastroNet-5M_DINOv1.pth")
for k in list(ckpt.keys()):
    print(k)

cls_token
pos_embed
patch_embed.proj.weight
patch_embed.proj.bias
blocks.0.norm1.weight
blocks.0.norm1.bias
blocks.0.attn.qkv.weight
blocks.0.attn.qkv.bias
blocks.0.attn.proj.weight
blocks.0.attn.proj.bias
blocks.0.norm2.weight
blocks.0.norm2.bias
blocks.0.mlp.fc1.weight
blocks.0.mlp.fc1.bias
blocks.0.mlp.fc2.weight
blocks.0.mlp.fc2.bias
blocks.1.norm1.weight
blocks.1.norm1.bias
blocks.1.attn.qkv.weight
blocks.1.attn.qkv.bias
blocks.1.attn.proj.weight
blocks.1.attn.proj.bias
blocks.1.norm2.weight
blocks.1.norm2.bias
blocks.1.mlp.fc1.weight
blocks.1.mlp.fc1.bias
blocks.1.mlp.fc2.weight
blocks.1.mlp.fc2.bias
blocks.2.norm1.weight
blocks.2.norm1.bias
blocks.2.attn.qkv.weight
blocks.2.attn.qkv.bias
blocks.2.attn.proj.weight
blocks.2.attn.proj.bias
blocks.2.norm2.weight
blocks.2.norm2.bias
blocks.2.mlp.fc1.weight
blocks.2.mlp.fc1.bias
blocks.2.mlp.fc2.weight
blocks.2.mlp.fc2.bias
blocks.3.norm1.weight
blocks.3.norm1.bias
blocks.3.attn.qkv.weight
blocks.3.attn.qkv.bias
blocks.3.attn.proj.wei

In [5]:
model = hiera_tiny_224()

In [3]:
import utils.lr_decay as lrd

In [6]:
param_groups = lrd.param_groups_lrd(model, weight_decay=0.05, no_weight_decay_list=model.no_weight_decay(), layer_decay=0.75)

parameter groups: 
{
  "layer_0_no_decay": {
    "lr_scale": 0.023757264018058777,
    "weight_decay": 0.0,
    "params": [
      "pos_embed",
      "patch_embed.proj.bias"
    ]
  },
  "layer_0_decay": {
    "lr_scale": 0.023757264018058777,
    "weight_decay": 0.05,
    "params": [
      "patch_embed.proj.weight"
    ]
  },
  "layer_1_no_decay": {
    "lr_scale": 0.03167635202407837,
    "weight_decay": 0.0,
    "params": [
      "blocks.0.norm1.weight",
      "blocks.0.norm1.bias",
      "blocks.0.attn.qkv.bias",
      "blocks.0.attn.proj.bias",
      "blocks.0.norm2.weight",
      "blocks.0.norm2.bias",
      "blocks.0.mlp.fc1.bias",
      "blocks.0.mlp.fc2.bias"
    ]
  },
  "layer_1_decay": {
    "lr_scale": 0.03167635202407837,
    "weight_decay": 0.05,
    "params": [
      "blocks.0.attn.qkv.weight",
      "blocks.0.attn.proj.weight",
      "blocks.0.mlp.fc1.weight",
      "blocks.0.mlp.fc2.weight"
    ]
  },
  "layer_2_no_decay": {
    "lr_scale": 0.04223513603210449,
    "we

In [5]:
input = torch.randn(4, 3, 224, 224)
output = model(input)
print(output.size())
print(torch.max(output), torch.min(output))

torch.Size([4, 1000])
tensor(0.0018, grad_fn=<MaxBackward1>) tensor(-0.0015, grad_fn=<MinBackward1>)
